#!/bin/sh 

/usr/bin/invoke_app "$@" -t matinformatics \
                         -C "start_jupyter -T @tool --themes index.ipynb" \
			 -u anaconda-7 \
                         -w headless \
			 -r none
